# Uncomment this line to define a global platform for your project
# platform :ios, ‘7.0’
# Uncomment this line if you're using Swift
# use_frameworks!

target 'kuaikanCartoon' do

#pod ‘iOS-WebP’, '0.4'
pod ’SDWebImage/WebP’
pod ‘MJRefresh’
pod ‘BlocksKit’
pod ‘AFNetworking’
pod ‘MBProgressHUD’
pod ‘Masonry’

end

