# Uncomment this line to define a global platform for your project
platform :ios, ‘7.0’
# Uncomment this line if you're using Swift
# use_frameworks!

target 'kuaikanCartoon' do

pod ’SDWebImage/WebP’
pod ‘MJRefresh’
pod ‘AFNetworking’
pod ‘Masonry’
pod ‘MJExtension’
pod ‘SVProgressHUD’

end

