# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'kuaikanCartoon' do

pod ‘AFNetworking’
pod ‘SDWebImage’
pod ‘MBProgressHUD’
pod ‘Masonry’
pod ‘MJRefresh’
pod ‘BlocksKit’

end

